#!/usr/bin/env python3
"""
Secondary validation for the top Hong Kong net-cash candidates.

Inputs are generated by outputs/hk_netcash_screen.py. This script focuses on
earnings durability and shareholder-return quality rather than raw screening
score.
"""

from __future__ import annotations

import json
import math
import os
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

import numpy as np
import pandas as pd

from hk_markdown import df_to_markdown


DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parents[1]
OUT = Path(os.environ.get("HK_NETCASH_OUTPUT_DIR", DEFAULT_OUTPUT_DIR)).resolve()
CACHE = OUT / "financial_cache"

INCOME_ALIASES = {
    "revenue": ["营业额", "经营收入", "经营收入总额", "营运收入"],
    "gross_profit": ["毛利"],
    "operating_profit": ["经营溢利"],
    "net_profit_owner": ["股东应占溢利"],
    "asset_sale_gain": ["出售资产之溢利"],
    "fair_value_gain": ["重估盈余", "按公平价值列账的金融资产公平值增加/减少"],
    "other_gains": ["其他收益", "其他收入"],
    "impairment": ["减值及拨备"],
}

CF_ALIASES = {
    "cfo": ["经营业务现金净额"],
    "dividend_paid": ["已付股息(融资)"],
    "buyback": ["回购股份"],
}

BS_ALIASES = {
    "cash": ["现金及等价物", "现金及现金等价物"],
    "short_deposit": ["短期存款", "定期存款", "存款"],
    "short_invest": ["短期投资", "证券投资", "指定以公允价值记账之金融资产(流动)", "其他金融资产(流动)"],
    "receivables": ["应收帐款", "应收账款", "预付款按金及其他应收款", "预付款项"],
    "inventory": ["存货"],
    "total_assets": ["总资产"],
    "total_liabilities": ["总负债"],
    "equity": ["股东权益", "股东权益合计", "归属于母公司股东权益", "净资产"],
}


def first(row: pd.Series, names: list[str]) -> float:
    for name in names:
        if name in row.index and pd.notna(row[name]):
            return float(row[name])
    return np.nan


def sum_present(row: pd.Series, names: list[str]) -> float:
    vals = [float(row[n]) for n in names if n in row.index and pd.notna(row[n])]
    return float(np.nansum(vals)) if vals else np.nan


def load_stmt(ts_code: str, endpoint: str) -> pd.DataFrame:
    path = CACHE / f"{ts_code.replace('.', '_')}.json"
    obj = json.loads(path.read_text())
    df = pd.DataFrame(obj.get(endpoint, {}).get("data", []))
    if df.empty:
        return df
    df = df.set_index("end_date")
    df.index = df.index.astype(str)
    for col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")
    return df.sort_index()


def annual(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df
    dec = df[df.index.str.endswith("1231")]
    return dec if len(dec) >= 2 else df.groupby(df.index.str[:4]).tail(1)


def cagr(vals: pd.Series) -> float:
    vals = vals.dropna()
    if len(vals) < 2:
        return np.nan
    first_v, last_v = float(vals.iloc[0]), float(vals.iloc[-1])
    n = len(vals) - 1
    if first_v <= 0 or last_v <= 0 or n <= 0:
        return np.nan
    return (last_v / first_v) ** (1 / n) - 1


def slope_flag(series: pd.Series) -> str:
    s = series.dropna()
    if len(s) < 3:
        return "样本不足"
    last = float(s.iloc[-1])
    prev = float(s.iloc[-2])
    high = float(s.max())
    if last <= 0:
        return "转亏或亏损"
    if high > 0 and last < high * 0.65:
        return "较高点回落明显"
    if prev > 0 and last < prev * 0.85:
        return "同比下滑明显"
    if prev > 0 and last > prev * 1.15:
        return "同比增长"
    return "大致稳定"


def pct(x: float) -> str:
    if pd.isna(x) or math.isinf(float(x)):
        return ""
    return f"{float(x) * 100:.1f}%"


def yi(x: float) -> str:
    if pd.isna(x):
        return ""
    return f"{float(x) / 1e8:.2f}"


def classify(row: dict) -> tuple[str, str]:
    red = []
    watch = []
    if "profit_warning" in row.get("hkex_flags", ""):
        red.append("近期披露易 profit warning")
    if row.get("oneoff_latest", 0) > 0.5:
        red.append("一次性/其他收益占利润>50%")
    if row.get("latest_payout", 0) > 1.2:
        watch.append("最近派息/利润>120%")
    if row.get("cfo_profit_avg4", 0) < 0.7:
        watch.append("4年CFO/利润均值偏低")
    if row.get("cfo_pos_years", 0) < 3:
        watch.append("经营现金流不够连续")
    if row.get("profit_trend") in {"同比下滑明显", "较高点回落明显"}:
        watch.append("利润趋势下滑")
    if row.get("revenue_trend") in {"同比下滑明显", "较高点回落明显"}:
        watch.append("收入趋势下滑")
    if row.get("profit_cagr4", 0) < -0.12:
        watch.append("利润趋势下滑")
    if row.get("revenue_cagr4", 0) < -0.10:
        watch.append("收入趋势下滑")
    if row.get("div_paid_years", 0) < 2 and row.get("shareholder_return_yield_est", 0) > 0.04:
        watch.append("主要靠回购，非稳定现金股息")
    if row.get("receivables_assets", 0) > 0.35:
        watch.append("应收/资产偏高")
    if row.get("property_chain", False):
        watch.append("地产/物业链口径需折价")
    if row.get("finance_like", False):
        watch.append("金融/放贷属性，净现金口径需折价")
    red = list(dict.fromkeys(red))
    watch = list(dict.fromkeys(watch))
    if red:
        return "C", "；".join(red + watch)
    if len(watch) >= 3:
        return "B-", "；".join(watch)
    if len(watch) >= 1:
        return "B", "；".join(watch)
    return "A", "暂未发现硬伤"


def main() -> None:
    ranked = pd.read_csv(OUT / "hk_ranked_candidates.csv").head(20)
    generated_at = datetime.now(ZoneInfo("Asia/Shanghai")).strftime("%Y-%m-%d %H:%M:%S %Z")
    quote_times = ranked["quote_time"].dropna().astype(str) if "quote_time" in ranked.columns else pd.Series(dtype=str)
    quote_meta = ""
    if not quote_times.empty:
        quote_meta = f"{quote_times.min()} 至 {quote_times.max()}"
    hkex_path = OUT / "top20_hkex_announcement_titles.csv"
    hkex = pd.read_csv(hkex_path) if hkex_path.exists() else pd.DataFrame(columns=["ts_code", "flags", "latest_titles"])
    hkex = hkex.rename(columns={"flags": "hkex_flags"})
    rows = []

    for source_rank, (_, base) in enumerate(ranked.iterrows(), start=1):
        code = base["ts_code"]
        inc = annual(load_stmt(code, "hk_income")).tail(4)
        cf = annual(load_stmt(code, "hk_cashflow")).tail(4)
        bs = annual(load_stmt(code, "hk_balancesheet")).tail(1)
        years = sorted(set(inc.index).intersection(cf.index))
        inc = inc.loc[years] if years else inc
        cf = cf.loc[years] if years else cf

        revenue = inc.apply(lambda r: first(r, INCOME_ALIASES["revenue"]), axis=1) if not inc.empty else pd.Series(dtype=float)
        profit = inc.apply(lambda r: first(r, INCOME_ALIASES["net_profit_owner"]), axis=1) if not inc.empty else pd.Series(dtype=float)
        cfo = cf.apply(lambda r: first(r, CF_ALIASES["cfo"]), axis=1) if not cf.empty else pd.Series(dtype=float)
        div_paid = cf.apply(lambda r: abs(first(r, CF_ALIASES["dividend_paid"])), axis=1) if not cf.empty else pd.Series(dtype=float)
        buyback = cf.apply(lambda r: abs(first(r, CF_ALIASES["buyback"])), axis=1) if not cf.empty else pd.Series(dtype=float)
        oneoff = inc.apply(
            lambda r: np.nansum(
                [
                    sum_present(r, INCOME_ALIASES["asset_sale_gain"]),
                    sum_present(r, INCOME_ALIASES["fair_value_gain"]),
                    sum_present(r, INCOME_ALIASES["other_gains"]),
                ]
            ),
            axis=1,
        ) if not inc.empty else pd.Series(dtype=float)

        latest_profit = profit.iloc[-1] if len(profit) else np.nan
        latest_revenue = revenue.iloc[-1] if len(revenue) else np.nan
        latest_cfo = cfo.iloc[-1] if len(cfo) else np.nan
        latest_div = div_paid.iloc[-1] if len(div_paid) else np.nan
        latest_buyback = buyback.iloc[-1] if len(buyback) else np.nan
        latest_oneoff = oneoff.iloc[-1] if len(oneoff) else np.nan
        cfo_profit_series = cfo / profit.replace(0, np.nan)
        payout_series = div_paid / profit.replace(0, np.nan)

        bs_row = bs.iloc[-1] if not bs.empty else pd.Series(dtype=float)
        receivables = sum_present(bs_row, BS_ALIASES["receivables"])
        inventory = sum_present(bs_row, BS_ALIASES["inventory"])
        total_assets = first(bs_row, BS_ALIASES["total_assets"])
        total_liabilities = first(bs_row, BS_ALIASES["total_liabilities"])
        cash_like = np.nansum(
            [
                sum_present(bs_row, BS_ALIASES["cash"]),
                sum_present(bs_row, BS_ALIASES["short_deposit"]),
                sum_present(bs_row, BS_ALIASES["short_invest"]),
            ]
        )

        h = hkex.loc[hkex["ts_code"] == code]
        hkex_flags = "" if h.empty else str(h.iloc[0].get("hkex_flags", ""))
        latest_titles = "" if h.empty else str(h.iloc[0].get("latest_titles", ""))
        name = str(base["name"])
        row = {
            "source_rank": source_rank,
            "ts_code": code,
            "name": name,
            "screen_score": base["score"],
            "price_hkd": base.get("price_hkd", np.nan),
            "quote_time": base.get("quote_time", ""),
            "quote_source": base.get("quote_source", ""),
            "market_cap_hkd": base["total_mv_hkd"],
            "turnover_hkd": base["turnover_hkd"],
            "pb": base["pb"],
            "pe_ttm": base["pe_ttm"],
            "report_years": ",".join(years),
            "latest_report_date": base["latest_report_date"],
            "revenue_latest": latest_revenue,
            "revenue_cagr4": cagr(revenue),
            "revenue_trend": slope_flag(revenue),
            "profit_latest": latest_profit,
            "profit_cagr4": cagr(profit),
            "profit_trend": slope_flag(profit),
            "profit_pos_years": int((profit > 0).sum()) if len(profit) else 0,
            "cfo_latest": latest_cfo,
            "cfo_pos_years": int((cfo > 0).sum()) if len(cfo) else 0,
            "cfo_profit_latest": latest_cfo / latest_profit if pd.notna(latest_profit) and latest_profit else np.nan,
            "cfo_profit_avg4": cfo_profit_series.replace([np.inf, -np.inf], np.nan).mean(),
            "oneoff_latest": latest_oneoff / abs(latest_profit) if pd.notna(latest_profit) and latest_profit else np.nan,
            "div_paid_years": int((div_paid.fillna(0) > 0).sum()) if len(div_paid) else 0,
            "div_paid_latest": latest_div,
            "buyback_latest": latest_buyback,
            "shareholder_return_latest": np.nansum([latest_div, latest_buyback]),
            "latest_payout": latest_div / latest_profit if pd.notna(latest_profit) and latest_profit else np.nan,
            "avg_payout4": payout_series.replace([np.inf, -np.inf], np.nan).mean(),
            "shareholder_return_yield_est": base["dividend_paid_yield_est"],
            "cash_to_liab": base["cash_to_liab"],
            "net_cash_to_mv": base["net_cash_to_mv"],
            "cash_like": cash_like,
            "total_liabilities": total_liabilities,
            "receivables_assets": receivables / total_assets if pd.notna(total_assets) and total_assets else np.nan,
            "inventory_assets": inventory / total_assets if pd.notna(total_assets) and total_assets else np.nan,
            "hkex_flags": hkex_flags,
            "hkex_latest_titles": latest_titles,
            "property_chain": any(k in name for k in ["物业", "生活服务", "服务", "星悦康旅", "彩生活"]),
            "finance_like": any(k in name for k in ["信贷", "汇彩"]),
            "pdf_status": "Tushare anns_d/report_rc 对港股为空；披露易标题已核验，年报PDF需网页/公司公告逐份补抓",
        }
        grade, concern = classify(row)
        row["secondary_grade"] = grade
        row["secondary_concern"] = concern
        rows.append(row)

    out = pd.DataFrame(rows)
    grade_order = {"A": 0, "B": 1, "B-": 2, "C": 3}
    out["grade_order"] = out["secondary_grade"].map(grade_order).fillna(9)
    out = out.sort_values(["grade_order", "screen_score"], ascending=[True, False]).drop(columns=["grade_order"])
    out.to_csv(OUT / "secondary_validation_top20.csv", index=False)

    display = out.copy()
    for col in ["market_cap_hkd", "turnover_hkd", "revenue_latest", "profit_latest", "cfo_latest", "div_paid_latest", "buyback_latest"]:
        display[col] = display[col].map(yi)
    for col in [
        "revenue_cagr4",
        "profit_cagr4",
        "cfo_profit_latest",
        "cfo_profit_avg4",
        "oneoff_latest",
        "latest_payout",
        "avg_payout4",
        "shareholder_return_yield_est",
        "cash_to_liab",
        "net_cash_to_mv",
        "receivables_assets",
    ]:
        display[col] = display[col].map(pct)
    display["screen_score"] = display["screen_score"].round(1)
    display["price_hkd"] = pd.to_numeric(display["price_hkd"], errors="coerce").round(3)
    cols = [
        "secondary_grade",
        "source_rank",
        "ts_code",
        "name",
        "screen_score",
        "price_hkd",
        "quote_time",
        "market_cap_hkd",
        "pb",
        "pe_ttm",
        "report_years",
        "revenue_trend",
        "profit_trend",
        "profit_pos_years",
        "cfo_pos_years",
        "cfo_profit_avg4",
        "oneoff_latest",
        "div_paid_years",
        "latest_payout",
        "shareholder_return_yield_est",
        "cash_to_liab",
        "net_cash_to_mv",
        "secondary_concern",
    ]
    md = [
        "# 前20名二次检验",
        "",
        "## 口径",
        "",
        "- Tushare 三表用于量化判断：收入、股东应占溢利、经营现金流、派息、回购、现金类资产和负债。",
        "- 稳定盈利不再只看正利润年数；这里加入趋势、现金流覆盖、一次性收益、派息透支和公告风险。",
        "- Tushare 的 `anns_d` 和 `report_rc` 对本批港股返回空，PDF/研报覆盖不足；已用披露易标题做时效性补充，完整年报 PDF 需逐家公司网页或披露易前端进一步补抓。",
        f"- 生成时间: {generated_at}；基于当前主榜前20，报价时间范围: {quote_meta or '无'}。",
        "- 表格按二次检验等级优先排序，`source_rank` 保留其在当前主榜中的原始排名。",
        "",
        "## 排序",
        "",
        df_to_markdown(display[cols], index=False),
        "",
    ]
    (OUT / "secondary_validation_top20.md").write_text("\n".join(md), encoding="utf-8")

    cards = []
    for _, r in display.iterrows():
        cls = "good" if r["secondary_grade"] == "A" else ("warn" if str(r["secondary_grade"]).startswith("B") else "bad")
        cards.append(
            f"""
<article class="vcard {cls}">
  <div class="vhead"><b>{r['secondary_grade']}</b><span>{r['ts_code']} {r['name']}</span><em>{r['screen_score']}</em></div>
  <div class="vgrid">
    <div><label>主榜排名</label><strong>{int(r['source_rank'])}</strong></div>
    <div><label>现价</label><strong>{r['price_hkd']}</strong></div>
    <div><label>报价时间</label><strong>{r['quote_time']}</strong></div>
    <div><label>市值</label><strong>{r['market_cap_hkd']}亿</strong></div>
    <div><label>PB/PE</label><strong>{r['pb']:.2f}/{r['pe_ttm']:.2f}</strong></div>
    <div><label>利润趋势</label><strong>{r['profit_trend']}</strong></div>
    <div><label>CFO/利润均值</label><strong>{r['cfo_profit_avg4']}</strong></div>
    <div><label>一次性占比</label><strong>{r['oneoff_latest']}</strong></div>
    <div><label>股东回报率</label><strong>{r['shareholder_return_yield_est']}</strong></div>
    <div><label>现金/负债</label><strong>{r['cash_to_liab']}</strong></div>
    <div><label>净现金/市值</label><strong>{r['net_cash_to_mv']}</strong></div>
  </div>
  <p>{r['secondary_concern']}</p>
</article>"""
        )
    html = f"""<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>前20名二次检验</title>
<style>
body{{margin:0;background:#f7f8fa;color:#17202a;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC',Arial,sans-serif}}
header{{position:sticky;top:0;background:rgba(247,248,250,.94);backdrop-filter:blur(10px);border-bottom:1px solid #dbe1e8;padding:12px 14px}}
h1{{font-size:20px;margin:0 0 4px}}.meta{{color:#637083;font-size:13px;line-height:1.45}}main{{max-width:1100px;margin:0 auto;padding:14px}}
.links{{display:flex;flex-wrap:wrap;gap:8px;margin:10px 0 16px}}.links a{{background:#176b87;color:white;text-decoration:none;padding:8px 10px;border-radius:6px;font-size:14px}}
.vcard{{background:white;border:1px solid #dbe1e8;border-left-width:5px;border-radius:8px;padding:12px;margin:10px 0}}.vcard.good{{border-left-color:#247a4d}}.vcard.warn{{border-left-color:#b77a1a}}.vcard.bad{{border-left-color:#a73838}}
.vhead{{display:flex;align-items:center;gap:8px}}.vhead b{{font-size:20px;min-width:32px}}.vhead span{{font-weight:700;flex:1}}.vhead em{{font-style:normal;color:#176b87;font-weight:700}}
.vgrid{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:10px}}.vgrid div{{background:#f3f6f8;border-radius:6px;padding:8px;min-width:0}}label{{display:block;color:#637083;font-size:12px;margin-bottom:3px}}strong{{font-size:14px;overflow-wrap:anywhere}}p{{color:#3d4a5c;font-size:13px;line-height:1.55}}
table{{width:100%;border-collapse:collapse;font-size:13px;min-width:1000px}}th,td{{padding:8px;border-bottom:1px solid #dbe1e8;text-align:right;white-space:nowrap}}th:nth-child(2),th:nth-child(3),td:nth-child(2),td:nth-child(3){{text-align:left}}.tablewrap{{overflow:auto;background:white;border:1px solid #dbe1e8;border-radius:8px}}
@media(min-width:760px){{.cards{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}}.vcard{{margin:0}}.vgrid{{grid-template-columns:repeat(4,minmax(0,1fr))}}}}
</style></head><body><header><h1>前20名二次检验</h1><div class="meta">生成时间：{generated_at}；基于当前主榜前20，报价时间范围：{quote_meta or '无'}。稳定盈利二次拆解：趋势、现金流覆盖、一次性收益、派息透支、披露易风险。</div></header>
<main><div class="links"><a href="index.html">返回主榜</a><a href="secondary_validation_top20.csv">CSV</a><a href="secondary_validation_top20.md">Markdown</a></div><section class="cards">{''.join(cards)}</section></main></body></html>"""
    (OUT / "secondary_validation_top20.html").write_text(html, encoding="utf-8")
    print(OUT / "secondary_validation_top20.csv")
    print(OUT / "secondary_validation_top20.md")
    print(OUT / "secondary_validation_top20.html")


if __name__ == "__main__":
    main()
